### ISSUE TITLE
Grey screen on teapot for one plus two and one plus three

### ISSUE THREAD

**Issue by Laeeth** [joakim-noah/android#11]
One plus three is running Android 7.1.1
One plus two 6.0.1

**Comment by joakim-noah** [comment]
[Both](https://browser.primatelabs.com/v4/compute/788679) [devices](http://browser.primatelabs.com/geekbench3/8321204) are running 64-bit Android, is it working for you on 32-bit Android?  We don't support 64-bit Android/AArch64 yet.  It's possible that it works on some 64-bit devices that allow running 32-bit libraries also, but that may not always work.

**Comment by joakim-noah** [comment]
I don't have access to a 64-bit Android device yet, see other issue where Petar is trying it out.  Hopefully, we'll get this working late this year, closing as unsupported for now.
