### ISSUE TITLE
Error while running ldc2-1.3.0-beta1-android-arm on a device

### ISSUE THREAD

**Issue by ZombineDev** [joakim-noah/android#9]
After installing Termux on Xiaomi Mi 5s (Android 6.0.1) and running the following commands:
```
curl -L -O https://github.com/joakim-noah/android/releases/download/tea/ldc2-1.3.0-beta1-android-arm.tar.xz
tar xf ldc2-1.3.0-beta1-android-arm.tar.xz
ldc2-1.3.0-beta1-android-arm/bin/ldc2 --version
```
I get:
```
CANNOT LINK EXECUTABLE: "/data/data/com.termux/files/usr/lib/libncursesw.so.6.0" is 64-bit instead of 32-bit
page record for 0xf71f904c was not found (block_size=64)
```

**Comment by joakim-noah** [comment]
The error message gives it away, [the Xiaomi Mi 5s is running a 64-bit AARCH64 kernel](https://browser.primatelabs.com/geekbench3/8369127), so Termux installs 64-bit versions of the packages, which don't work with this 32-bit native compiler.  I'd like to support Android/AArch64 someday, but I don't have any 64-bit hardare yet.  When I do, I'll put out a build for you. :)

**Comment by ZombineDev** [comment]
> the Xiaomi Mi 5s is running a 64-bit AARCH64 kernel

Yeah, I knew the cause of the issue already (sorry for not making that clear) . I was expecting a fully statically linked binary, and that's why I was surprised by the error.
While AArch64 would be nice, I am only interested of ARMv7. Correct me if I am wrong, but running ARMv7 on ARMv8 AArch64 shouldn't be a problem, just like running i386 on x86_64 is not? So the only thing needed should be an ARMv7 version​ of libncursesw, right?

**Comment by ZombineDev** [comment]
BTW, there's a related termux issue: https://github.com/termux/termux-packages/issues/214 so it possible that it's a termux packaging issue.

**Comment by joakim-noah** [comment]
Yeah, you should be able to run 32-bit ARMv7 binaries on AArch64 as long as the software supports it, as we discussed on the forum.  I don't know to what extent the Termux you install on Android/AArch64 provides those 32-bit libraries also in its packages.

You could investigate by checking what files the `ncurses` package installs (`dpkg -L ncurses`) and then run `file` on the installed libraries to see what version they are.
